// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxFz50sg4f_xVKXQFFCLuCmAojtDDUT_w',
    appId: '1:1000019966117:web:080f52ae4a943b396d754c',
    messagingSenderId: '1000019966117',
    projectId: 'projeto-aviario-7f939',
    authDomain: 'projeto-aviario-7f939.firebaseapp.com',
    storageBucket: 'projeto-aviario-7f939.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyOhcJ86V6El5k7i9pqW6zTT8gGjXm3jg',
    appId: '1:1000019966117:android:2034b72a67ecc8a96d754c',
    messagingSenderId: '1000019966117',
    projectId: 'projeto-aviario-7f939',
    storageBucket: 'projeto-aviario-7f939.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOolpVVJ_SQ-7-alTd3fOlcaRF00BFqqU',
    appId: '1:1000019966117:ios:756a10ddd31385856d754c',
    messagingSenderId: '1000019966117',
    projectId: 'projeto-aviario-7f939',
    storageBucket: 'projeto-aviario-7f939.firebasestorage.app',
    iosBundleId: 'com.example.projetoDdm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOolpVVJ_SQ-7-alTd3fOlcaRF00BFqqU',
    appId: '1:1000019966117:ios:756a10ddd31385856d754c',
    messagingSenderId: '1000019966117',
    projectId: 'projeto-aviario-7f939',
    storageBucket: 'projeto-aviario-7f939.firebasestorage.app',
    iosBundleId: 'com.example.projetoDdm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxFz50sg4f_xVKXQFFCLuCmAojtDDUT_w',
    appId: '1:1000019966117:web:4e7b7701285eb02c6d754c',
    messagingSenderId: '1000019966117',
    projectId: 'projeto-aviario-7f939',
    authDomain: 'projeto-aviario-7f939.firebaseapp.com',
    storageBucket: 'projeto-aviario-7f939.firebasestorage.app',
  );
}
